import { SharedLayout } from '@nx-monorepo/shared-layout';
export const metadata = {
  title: 'Welcome to demo2',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
          <SharedLayout>
          {children}
          </SharedLayout>
      </body>
    </html>
  );
}
